# Tutoriales DeepXDE

Basados en los videos:
https://www.youtube.com/playlist?list=PLM7DTyYjZGuLYDLV9g7AqkEatySe-lAqG

# Tutorial 1
### DeepXDE Setup and Overview 


DeepXDE es una librería, una muy poderosa para solucionar ecuaciones diferenciales parciales.
La página oficial es: https://deepxde.readthedocs.io/en/latest/index.html

DeepXDE is a library for scientific machine learning and physics-informed learning. 





# Que es un backend:

Son librerias que manejan diferentes redes neuronales. 
    The underlying library or framework that handles the low-level computational operations, such as matrix multiplication, gradient calculations, and model optimization. It's the engine that powers the neural network's training and inference. 

DeepXDE es compatible con los backends de TensorFlow 1.x ( tensorflow.compat.v1en TensorFlow 2.x), TensorFlow 2.x, PyTorch, JAX y PaddlePaddle.

> DDE_BACKEND=tensorflow.compat.v1 python pde.py

> DDE_BACKEND=tensorflow python pde.py

> DDE_BACKEND=pytorch python pde.py

> DDE_BACKEND=jax python pde.py

> DDE_BACKEND=paleta python pde.py

- No hay un backend que sea siempre más rápido que los demás.

- La velocidad depende del problema específico, el tamaño del conjunto de datos, su hardware, etc. En algunos casos, un backend podría ser significativamente más rápido que otros, como 4 veces más rápido.

- Si no está seguro de cuál es el más rápido para su problema, en general recomendamos TensorFlow 2.x, porque encontramos que en algunos casos TensorFlow 2.x > PyTorch > TensorFlow 1.x (> significa más rápido).

In [1]:
import deepxde as dde
import tensorflow as tf # It was created by developers at Google and released in 2015
import numpy as np
dde.backend.backend_name = "pytorch"

import torch as tr

2025-05-29 14:49:40.310621: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1748551780.389141    6252 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1748551780.395375    6252 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-05-29 14:49:40.414752: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Using backend: tensorflow
Other supported backends: tensorflow.compat.v1, pytorch, jax, paddle.
paddle supports more examples

In [ ]:
dde.backend.set_backend("tensorflow")

print("DeepXDE version:", dde.__version__)
print("TensorFlow version:", tf.__version__)
print("NumPy version:", np.__version__)
print("Backend en uso:", dde.backend.backend_name)

## Diferencia entre pytorch y tensorflow

Fuente: https://builtin.com/data-science/pytorch-vs-tensorflow

- PyTorch es un marco de aprendizaje profundo relativamente joven que es más compatible con Python y es ideal para investigación, creación de prototipos y proyectos dinámicos.  Fue creado por el equipo de Meta AI y publicado en código abierto en GitHub en 2017}


- TensorFlow es un framework de aprendizaje profundo consolidado con potentes capacidades de visualización y diversas opciones para el desarrollo de modelos de alto nivel. Ofrece opciones de implementación listas para producción y compatibilidad con plataformas móviles.

## Metodo data:

<code>
data = dde.data.PDE(
        geometry,
        pde,
        bcs,
        num_domain=0,
        num_boundary=0,
        train_distribution="Hammersley",
        anchors=None,
        exclusions=None,
        solution=None,
        num_test=None,
        auxiliary_var_function=None,
    )
    
    Args:
        geometry: Instance of ``Geometry``.
        pde: A global PDE or a list of PDEs. ``None`` if no global PDE.
        bcs: A boundary condition or a list of boundary conditions. Use ``[]`` if no
            boundary condition.
        num_domain (int): The number of training points sampled inside the domain.
        num_boundary (int): The number of training points sampled on the boundary.
        train_distribution (string): The distribution to sample training points. One of
            the following: "uniform" (equispaced grid), "pseudo" (pseudorandom), "LHS"
            (Latin hypercube sampling), "Halton" (Halton sequence), "Hammersley"
            (Hammersley sequence), or "Sobol" (Sobol sequence).
        anchors: A Numpy array of training points, in addition to the `num_domain` and
            `num_boundary` sampled points.
        exclusions: A Numpy array of points to be excluded for training.
        solution: The reference solution.
        num_test: The number of points sampled inside the domain for testing PDE loss.
            The testing points for BCs/ICs are the same set of points used for training.
            If ``None``, then the training points will be used for testing.
        auxiliary_var_function: A function that inputs `train_x` or `test_x` and outputs
            auxiliary variables.

</code>


#### Ejemplo:

```Python
## Data model:
data = dde.data.PDE(geom,
                    pde,
                    [bc_dbc,bc_nbc,bc_obc1,bc_obc2],
                    20,         # No of collocation points
                    2,          ## SON PUNTOS EN LA FRONTERA, NO NUMERO DE BC. POR ESO ES 2 NO 4.
                    solution=func,
                    num_test=100
                   )
# Why the number test is higher than the training points. 
# El Numero test de este ejemplo es de 100
# mientras que el numero de ptos de entrenamiento son 22 = 20+2.
# num_test se refiere al número de puntos a lo largo del cual el dominio y la frontera son evaluados
# depues del entrenamiento
# El numero de collocation points son escogidos en base de la presición deseada de los resultados. 
# Si las predicciónes son pobres, quizas se deba incrementar el número. Pero si las predicciones
# son muy buenas se debe bajar en orden de reducir el costo computacional.

# Otra cosa es que en PINNs no tenemos ningun dato predefinido. Nosotros generamos nuestros 
# propios datos usando los puntos de colocación.  Así que somos libres de escoger cualquier 
# numero, solo teniendo en cuenta que esto aumenta el costo computacional
```

Entonces, Necesito entender:

- ***train_distribution***
- auxiliary_var_function

In [ ]:
   self,
        geometry,
        pde,
        bcs,
        num_domain=0,
        num_boundary=0,
        train_distribution="Hammersley",
        anchors=None,
        exclusions=None,
        solution=None,
        num_test=None,
        auxiliary_var_function=None,
    ):

## Number of Collocation Points (Points where the network is trained to satisfy the PDE	)

Training


El valor 16 se refiere al número de puntos de colocación por batch. Estos son los puntos interiores muestreados dentro del dominio definido por geom, donde la red neuronal se entrena para satisfacer la ecuación diferencial. Los puntos de colocación se utilizan para calcular los residuos de la PDE durante el entrenamiento; es decir, el grado en que la solución de la red neuronal satisface la PDe en esos puntos específicos. La red minimiza estos residuos mediante retropropagación.


Por lo tanto, los puntos de colocación no evalúan la precisión; son los "datos de entrenamiento" generados a partir de la EDP y la geometría.

## num_test=100 (Points where the model is evaluated against the exact solution	)


Evaluation / Testing


Especifica el número de puntos de prueba, es decir, los puntos utilizados para evaluar el rendimiento del modelo entrenado. En estos 100 puntos:

El modelo entrenado predice valores. Estas predicciones se comparan con los valores reales (de solution=func, la solución exacta o conocida). Se calculan métricas como el error L2 para evaluar la precisión del modelo.

## Como calcular derivadas:

Differenciación automática. Autodiff

1. Jacobian
    - Para una función escalar f(x) el Jacobiano es simplemente la primera derivada 
    - para una funcion multivariable f(x,y), el jacobiano es un vector de las derivadas parciales respecto a cada variable
2. Hessian
    - El Hesiano es una matris de segundas derivadas parciales
    - Para una función escalar f(x) es solo la segunda derivada respecto a x
    - Para una función f(x,y) es una matris que incluye todas las posibles segundas derivadas

<br> 

### Por ejemplo: <br> 
Para una función $f(x,y)=x^2+xy+y^2$,<br> 

1. Jacobiano:<br> 
    - .  $\frac{\partial f}{\partial x} = 2x+y$<br> 
    - . $\frac{\partial f}{\partial y} = x+2y$<br> 
    El vector sería $$Jacobian = \left[ \begin{matrix}
2x + y\\
x + 2y 
\end{matrix}\right]$$

2. Hessiano:<br> 
    - .  $\frac{\partial^2 f}{\partial x^2} = 2$<br> 
    - . $\frac{\partial^2 f}{\partial y^2} = 2$<br>  
    - . $\frac{\partial^2 f}{\partial x \partial y} = 1$<br> 
    - . $\frac{\partial^2 f}{\partial y \partial x} = 1$<br> 
    El vector sería $$Hessian = \left[ \begin{matrix}
2 & 1\\
1 & 2 
\end{matrix}\right]$$


> dde.grad.hesian(y,x)

## Tipos de Condiciones de Frontera:

Fuente: https://deepxde.readthedocs.io/en/latest/modules/deepxde.icbc.html


**1. DirichletBC**
```Python
dde.icbc.DirichletBC(geom, boundary_func, boundary)
```
Donde:
    
```Python
def boundary(x, on_boundary):
    return on_boundary and dde.utils.isclose(x[0],-1)
def boundary_func(x):
    return 0 
```

**2. NeumannBC**
```Python
dde.icbc.NeumannBC(geom, boundary_func,boundary)
```
Donde:
    
```Python
def boundary(x, on_boundary):
    return on_boundary and dde.utils.isclose(x[0],1)
def boundary_func(x):
    return 4 
```

Acá se fija $(du/dx=4)$

**3. RobinBC**

Las condiciones de frontera Robin son una mexcla de las condiciones de frontera de dirichlet y las de neumann.
Estas condiciones de frontera  (Junto con la BC periódica) son tareas más críticas que aveces incluso pueden introducir inestabilidades en el entrenamiento lo que puede llebar a una solucion de la red debil.

```Python
dde.icbc.RobinBC(geom, boundary_func,boundary)
```
Donde:
    
```Python
def boundary_flux_r(x,y):  #<--- Ahora tiene dos argumentos
    return y #Sets du/dx=u at all x=1

def boundary_r(x,on_boundary):
    return on_boundary and dde.utils.isclose(x[0],1)
```
La función de frontera, **boundary_func**
Acá se fija $$a\cdot u + b\cdot \frac{du}{dx}=g$$ donde $a$, $b$, $g$ son constantes o funciones.



**4. PeriodicBC**

Las condiciones de frontera periodicas implican que la solucion debe tener el mismo valor en puntos pares atravez de fronteras opuestas, creando una solucion cíclica.

Estas condiciones de frontera  (Junto con la BC Robin) son tareas más críticas que aveces incluso pueden introducir inestabilidades en el entrenamiento lo que puede llebar a una solucion de la red debil.

```Python
dde.icbc.PeriodicBC(geom, component_x, on_boundary,derivative_order=0,component=0)
```
Donde:
```Python
component_x  # <---- Especifica el eje o la dimension espacial a lo largo de la cual se pide la periodicidad
             #       No es una coordenada específica
             #       En una geometria tipo rectangulo (x,y), component_x=0 pone periodicidad en el eje x
             #                                             y component_x=1 pone periodicidad en el eje y
on_boundary  # <---- La misma función boleana de antes.

derivative_order=0 # <---- Por defaut = 0. Especifica si la condición de periodicidad es sobre la función 
                   #       o sobre algun orden de derivada. Si = 1 => u'(a)=u'(b) 
component=0  # <---- Si se soluciona una PDE con más incognitas, ej. u,v. component=0 -> u(x,y)
             #                                                            component=1 -> v(x,y)
``` 


##### Ejemplo:

```Python
def on_boundary(x,on_boundary):
    return on_boundary 

bc_r=dde.icbc.PeriodicBC(geom, 0,boundary_r)
```
##### Extra de condiciones de frontera:
Tambien soporta dos funciones complementarias. 
- **collocation_points** Retorna las coordenadas de los puntos donde la periodicidad está siendo aplicada.
```Python
X= geom.uniform_points(10) # Genera 10 puntos en el intervalo [-1,1]
periodic_points = bc_r.collocation_points(X)  # <- arroja solo -1 y 1
```


- **error**  Return the loos <br>

> error[X, inputs,outputs,beg,end,aux_var=None]

```Python
X= geom.uniform_points(10)                             # Genera 10 puntos en el intervalo [-1,1]
periodic_points = bc_r.collocation_points(X)           # solo -1 y 1
inputs  = tr.tensor(periodic_points, dtype=tr.float32) # Un tensor de -1 y 1
outputs = tr.tensor(model.predict(periodic_points), dtype=tr.float32) # Tensor de la solucion encontrada en 
                                                                      # la frontera
    
# Defining the range for beg and end indices for the paired points
beg, end = 0, len(periodic_points)
residual = bc_r.error(X, inputs, outputs, beg, end)

# The Mean Squared Error MSE
mse_residual = tr.mean(residual**2)  
print("MSE of boundary residual for periodic condition (u(-1)- u(1)):", mse_residual.item())
```

Si queremos condiciones periodicas sobre puntos que no son la frontera, por ejemplo, $x\in[-1,1]$ y $u(-1)=u(0)$, ya no se puede usar este objeto. Se usan otras BC llamadas OperatorBC.





**5. OperatorBC**


Son tambien conocidas como condiciones de frontera no estandar.<br>
Algunos ejemplos serian:
1. Higher - Order Boundary Conditions
$$u''(1)=0,\qquad u'''(1)=0$$
2. Nonlinear Boundary Conditions
$$u'(1)+u(1)^2=0,$$
3. Mixed-Type Conditions
$$u'(0)+\sin(u(1))=0,$$

Este tipo de condiciones no puede ser usado por ninguna forma estandar.


La clase OperatorBC permite forzar condiciones de frontera generales de un cierto operador. A diferencia de las condiciones de frontera estandar, este deha definir constricciones personalizadas que involucran operaciones en las entradas salidas y derivadas. Es de la forma $$f(inputs,outputs,X)=0$$ donde:
- **inputs**: Valores de entrada del modelo (ej. Coordenadas espaciales)
- **outputs**: Valores de predichos por el modelo 
- **x**: El arreglo de los puntos inputs originales

**Los inputs/outputs deben darse en la forma de un tensor dependiendo de la libreria. (Pytorch o Tensorflow)**

#### Syntax

```Python
dde.icbc.OperatorBC(geom, func, on_boundary)
```
Donde:
- **func** Es la funcion que define la condicion de frontera. Esta debe tomar 3 argumentos. Inputs, outputs y x. La función debe retornat una tensor del tipo $N \times 1$ donde N es el número de puntos en la frontera.
- on_boundary. Una funcion boleana como las anteriores con x el punto y on_boundary el valor boleano.


## Soft and hard Boundary Conditions
 - Soft BC permite cierta flexibilidad, lo que puede resultar en algunos pequeños errores. $1e-8$ por ejemplo
 - Hard BC se fuerza estrictamente a satisfacer las BC
 
 Para esto tambien se usa el operadorBC

## Initializer option

Funcion que inicializa para todas las capas ocultas y neuronas

- used during forward passes, affects the nonlinearity of your network.


<code>
"tanh",    # "Hyperbolic tangent. Smooth and commonly used in PINNs.",
"relu",    # "Rectified Linear Unit. Simple and fast, but can lead to dead neurons.",
"sigmoid", # "Sigmoid function. Rarely used in PINNs due to vanishing gradients.",
"sin",     # "Sine function. Good for problems with periodic behavior.",
"swish",   # "Smooth, non-monotonic function. Often performs better than ReLU.",
"gelu",    # "Gaussian Error Linear Unit. Smooth and effective in some contexts.", - >No funciona
"silu",    # "Sigmoid-weighted Linear Unit. Alias for swish.",
"mish" 
</code>
 

## Weight initializer 

Se inicializa el conjunto inicial de pesos y biases

- used once, at the beginning, affects the starting values of the weights.

<code>
"Glorot normal"
        "Glorot uniform"
        "He normal"
        "He uniform"
        "LeCun normal"
        "LeCun uniform"
        "Orthogonal"
        "zeros"
        # Initializers of stacked DeepONet
        "stacked He normal"
        "stacked He uniform"
        "stacked LeCun normal"
        "stacked LeCun uniform"
</code>
 
 
 
These two affect how well the initial loss behaves. And the initial loss affects how fast and stable training begins.

# Comparación entre 

The first row of the table defines the headers, then the next row defines the alignment of each column. You duplicated the alignment at the top of the table and where it's actually supposed to go.

The right Markdown should simply be what you have in your syntax, but remove the first row:

| Característica | **model.predict** | **model.net** |
| --- | --- | --- |
| **Propósito** | Método de alto nivel para generar predicciones. Maneja el procesamiento input/output automáticmaente| Acceso directo a la red neuronal subyacente para operacioness personalizadas. |
| **Input type** | Espera inputs tipo numpy arrays | Espera inputs como tensores del backend específico (ej. pytorch o tensorflow |
| **Output type** | Retorna Outputs como arreglos de Numpy, separados de la grafica computacional | Retorna tensores  |
| **Gradient Tracking** | No gradient tracking is supported | Gradients are tracked, making 
| **Use Case** |
| **Flexibility** |
| **Connection to backend** |
| **Operation Supported** |
| **Common Syntax** |
| **Example Usage** |

## What is a Computational Graph?
A computational graph is a structure that tracks the operations and data dependencies used to compute outputs from inputs, so that gradients can be automatically computed during backpropagation.

## ¿Qué es un grafo computacional?
Un grafo computacional es una estructura que representa todas las operaciones que se hacen sobre los tensores. Sirve para que el sistema pueda calcular automáticamente los gradientes necesarios durante el entrenamiento (esto se llama autograd o diferenciación automática).

### Tensor conectado al grafo
Un tensor está conectado al grafo computacional cuando:

- Guarda el historial de operaciones hechas sobre él.

- Permite calcular derivadas (gradientes).

- Es necesario para el entrenamiento, cuando haces backward() para optimizar los pesos del modelo.

En DeepDXD, esto lo obtienes cuando llamas a model.net(...).

In [11]:
x = tr.tensor([1.0], requires_grad=True)
x

tensor([1.], requires_grad=True)

In [17]:
z = (x**2 + 3*x +2) * tr.sin((x))   # y está conectado a x


In [13]:
y.backward()  # calcula el gradiente dy/dx

In [18]:
x

tensor([1.], requires_grad=True)

In [19]:
z

tensor([5.0488], grad_fn=<MulBackward0>)

In [20]:
x.grad

tensor([2.])